services:
  sqlserver:
    container_name: bikefit-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
      MSSQL_PID: "Developer"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
  
  backend:
    container_name: bikefit-backend
    build:
      context: ./bikefit-backend
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: "${SA_PASSWORD}"
      DB_DATABASE: bikefit
    depends_on:
      sqlserver:
        condition: service_healthy

  frontend:
    container_name: bikefit-frontend
    build:
      context: ./bikefit-frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      REACT_APP_API_URL: http://backend:3001
    depends_on:
      - backend

volumes:
  sqlserver_data: